config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

    #signing up
    get '/signup', to: 'users#new'
    post '/signup', to: 'users#create'
  
    #logging in
    get 'auth/:provider/callback', to: 'sessions#omniauth'
    get '/login', to: "sessions#new"
    post '/login', to: "sessions#create"
    delete '/logout', to: "sessions#destroy"

  #get 'popular_category' => "popular_category"  
  resources :categories do
    resources :products, only: %i[index new create]
  end

  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"

  post 'order_items/:id/add' => "order_items#add_quantity", as: "order_item_add"
  post 'order_items/:id/reduce' => "order_items#reduce_quantity", as: "order_item_reduce"
  post 'order_items' => "order_items#create"
  get 'order_items/:id' => "order_items#show", as: "order_item"
  delete 'order_items/:id' => "order_items#destroy"

  resources :users, except: :new
  resources :products
  resources :admins
  resources :orders
 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  # get '/users/reset_password', to: 'users#reset_form'
  # post '/users/reset_password', to: 'users#password_reset'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :order_items, dependent: :destroy
    has_many :products, through: :order_items
    has_many :orders, through: :order_items

    def sub_total
        sum = 0
        self.order_items.each do |order_item|
          sum+= order_item.total_price
        end
        return sum
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

    def show
        @cart = @current_cart
      end
    
      def destroy
        @cart = @current_cart
        @cart.destroy
        session[:cart_id] = nil
        redirect_to root_path
      end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<fieldset>
<h2>Cart</h2>

<% if @cart.order_items.size == 0 %>
  <div class="center text-center">
    <p>Your shopping cart is currently empty.</p>  
    <p><%= link_to "Go back.", products_path %> </p>
  </div>
<% else %>

<ul>
  <% @cart.order_items.each do |order_item| %>
      <p>Item: <%= link_to order_item.product.name, order_item.product %></p>
      <p>Price: <%= number_to_currency(order_item.total_price) %></p>
      <p>Quantity: <%= order_item.quantity %></p>
  <ul>
      <li>
        <%= link_to "Add (+1)", order_item_add_path(:id => order_item), method: :post %>
        <%= link_to "Reduce (-1)", order_item_reduce_path(:id => order_item), method: :post %>
      </li>
      <li>
        <%= link_to "Remove item", order_item_path(order_item), method: :delete %>
      </li>
    </ul>
    <hr>  
  <% end %>
</ul>
  <h3>Sub total: <%= number_to_currency(@cart.sub_total) %></h3>
  <%= link_to "Proceed to checkout", new_order_path %><br>
  <%= link_to "Empty cart", cart_path(@current_cart),method: :delete, data: {confirm: "Are you sure?"} %>
<% end %>

</fieldset>