config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

    #signing up
    get '/signup', to: 'users#new'
    post '/signup', to: 'users#create'
  
    #logging in
    get 'auth/:provider/callback', to: 'sessions#omniauth'
    get '/login', to: "sessions#new"
    post '/login', to: "sessions#create"
    delete '/logout', to: "sessions#destroy"

  #get 'popular_category' => "popular_category"  
  resources :categories do
    resources :products, only: %i[index new create]
  end

  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"

  post 'order_items/:id/add' => "order_items#add_quantity", as: "order_item_add"
  post 'order_items/:id/reduce' => "order_items#reduce_quantity", as: "order_item_reduce"
  post 'order_items' => "order_items#create"
  get 'order_items/:id' => "order_items#show", as: "order_item"
  delete 'order_items/:id' => "order_items#destroy"

  resources :users, except: :new
  resources :products
  resources :admins
  resources :orders
 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  # get '/users/reset_password', to: 'users#reset_form'
  # post '/users/reset_password', to: 'users#password_reset'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products

    validates :name, presence: true, uniqueness: true

    scope :alpha, -> {order('name')}
    scope :popular_category, -> {joins(:products).group("products.category_id").order("count(products.category_id) DESC").limit(1)}

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :redirect_unless_admin, only: [:new, :edit, :update, :destroy]
    before_action :find_category, only: [:show, :edit, :update, :destroy]

    def index
        @categories = Category.alpha
    end

    def new
        @category = Category.new
        @category.products.build
    end

    def create
        @category = Category.create(category_params)
        if @category.valid?
            redirect_to @category
        else
            @category.products.build
            render :new
        end
    end

    def show
    end

    def edit
        if logged_in?
            @category = Category.find_by(id: params[:id])
        else
            redirect_to category_path(@category)
        end
    end

    def update
        @category.update(category_params)
        if @category.valid?
            redirect_to @category
        else
            render :edit
        end
    end

    def destroy
        if @category.destroy
            redirect_to categories_path
        else
            redirect_to @category
        end
    end

    private

    def category_params
        params.require(:category).permit(:name, :decription)
    end

    def find_category
        @category = Category.find_by(id: params[:id])
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
    def active_css(path)
        "active" if current_page?(path)
    end

    def display_h1_conditionally(resource)
        if resource
            content_tag(:h1, "#{resource.name}'s Catalog", class: "products-h1-header")
        else
            content_tag(:h1, "All Products", class: "products-h1-header")
        end
    end
    
end

app/views/categories/_category.html.erb
<div class= "brand table-cell">
    <%= link_to category.name, category_products_path(@category) %> (<%= category.products.size %>)
</div>

app/views/categories/_form.html.erb
<div class="form-input">
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: 'Category Name'%>
</div>
<div class="form-input">
    <%= f.label :description %>
    <%= f.text_area :description, placeholder: 'Category Description' %>
</div>

app/views/categories/edit.html.erb
<h1>Edit <%= @category.name%></h1>

<div class="new-form">
    <%= form_with(model: @category) do |f| %>
        <%= render partial: "form", locals: {f: f}%>
        <div class="form-button"><%= f.submit %></div>
    <% end %>
    <div class="form-button"><%= button_to "Delete", category_path(@category), method: :delete, data: {confirm: "Are you sure?"} %></div> <br>
</div>


<%= link_to "New Category", new_category_path %><br><br>
<%= link_to 'View All Categories', categories_path %>

app/views/categories/index.html.erb
<h1> Categories </h1>

<div class="new-form">
        <% @categories.each do |category| %>
            <p><%= link_to category.name, category %>(<%= category.products.size %>)</p>
            <p><%= category.description %></p>
        <% end %>
    </ul>
</div>

app/views/categories/new.html.erb
<%= conditional_errors(@category) %>

<div class="new-form">
    <header>
        <h2>Create a New Category</h2>
    </header>
    <%= form_with(model: @category) do |f| %>
        <%= render partial: "form", locals: {f: f}%>
        
        <div class="form-input">
            <h3>Create a new product (optional)</h3>
            <%= f.fields_for :products do |products_fields| %>
                <div class="form-input">
                    <%= products_fields.label :name %>
                    <%= products_fields.text_field :name%>
                </div>

                <div class="form-input">
                    <%= products_fields.label :descrption %>
                    <%= products_fields.text_field :descrption%>
                </div>
                <div class="form-input">
                    <%= products_fields.label :availability %>
                    <%= products_fields.select :availability, options_for_select([true, false]), include_blank: "Select an availability" %>
                </div>
                <div class="form-input">
                    <%= products_fields.label :price %>
                    <%= products_fields.number_field :price, step: 0.01%><br>
                </div>
                <div class="form-input">
                    <%= products_fields.label :category %>
                    <%= products_fields.select :category, options_for_select([ "clothing", "accessories", "electronics", "groceries"]), include_blank: "Select a category"%>
                </div>
            <% end %>
        </div>
        <div class="form-button"><%= f.submit %></div>
    <% end %>
</div>

<%= link_to 'View Categories', categories_path %>

app/views/categories/show.html.erb
<fieldset>
<h1> <%= @category.name %> </h1>

<div>
    <%= render partial: "category", locals: { category: @category } %>
    <p><%= @category.description %></p>
</div>
</fieldset>

<% if user_admin %>
    <%= link_to 'Edit Category', edit_category_path(@category) %> |
<% end %>
<%= link_to 'Back', categories_path %>