config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

    #signing up
    get '/signup', to: 'users#new'
    post '/signup', to: 'users#create'
  
    #logging in
    get 'auth/:provider/callback', to: 'sessions#omniauth'
    get '/login', to: "sessions#new"
    post '/login', to: "sessions#create"
    delete '/logout', to: "sessions#destroy"

  #get 'popular_category' => "popular_category"  
  resources :categories do
    resources :products, only: %i[index new create]
  end

  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"

  post 'order_items/:id/add' => "order_items#add_quantity", as: "order_item_add"
  post 'order_items/:id/reduce' => "order_items#reduce_quantity", as: "order_item_reduce"
  post 'order_items' => "order_items#create"
  get 'order_items/:id' => "order_items#show", as: "order_item"
  delete 'order_items/:id' => "order_items#destroy"

  resources :users, except: :new
  resources :products
  resources :admins
  resources :orders
 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  # get '/users/reset_password', to: 'users#reset_form'
  # post '/users/reset_password', to: 'users#password_reset'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :category
    has_many :order_items
    has_many :orders, through: :order_items
    has_many :carts, through: :order_items


    validates :name, presence: true, uniqueness: true
    validates :price, presence: true
    
    scope :search_by_name, -> (search) {where("name LIKE ?", "#{search}%")}
    scope :latest_products, -> {order(created_at: :desc)}
    scope :available_products, -> {where(availability: "true").order("name")}
    scope :out_of_stock, -> {where(availability: "false").order("name")}

    def category_attributes=(attributes)
        if !attributes["name"].blank?
            self.category = Category.find_or_create_by(attributes)
        end
    end

    def in_stock?
        if self.availability
            "In stock"
        else
            "Out of Stock"
        end
    end
    
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :redirect_unless_admin, only: [:new, :edit, :update, :destroy]
    before_action :find_product, only: [:show, :edit, :update, :destroy]
    
    def index
        if params["search"]
            @products = Product.search_by_name(params["search"])
        elsif params[:category_id] && @category = Category.find(params[:category_id])
            @products = @category.products
        else
            @products = Product.latest_products
        end
    end

    def show
        find_product
    end

    def new  
        if params[:category_id] && @category = Category.find_by(params[:category_id])
            @product = Product.new(category_id: params[:category_id])
        else
            @product = Product.new
            build_category
        end   
    end

    def create
        @product = Product.new(product_params)
        @category = Category.find(params[:category_id]) if params[:category_id]
        
        if @product.save
            redirect_to @product
        else
            build_category
            render :new
        end
    end

    def edit
    end

    def update
        @product.update(product_params)
        if @product.valid?
            redirect_to @product
        else
            build_category
            render :edit
        end
    end

    def destroy
        if @product.destroy
            redirect_to products_path
        else
            redirect_to back
        end
    end

    private

    def product_params
        params.require(:product).permit(:name, :description, :availability, :price, :category_id, category_attributes: [:name, :description])
    end

    def build_category
        @product.build_category
    end

    def find_product
        @product = Product.find_by_id(params[:id])
    end

end

app/helpers/products_helper.rb
module ProductsHelper
    def nested_product_form_conditional(resource, nested_resource, f)
        if !nested_resource
            render partial: "nested_category", locals: {f: f, product: resource}
        else
            f.hidden_field :category_id, value: nested_resource.id
        end
    end
end

app/views/products/_errors.html.erb
<div class="error-explanations">
    <h2><%=pluralize(object.errors.count, "Error") %> prevented the <%= object.class.to_s %> from being created:</h2>
    <ul class="error-details">
        <% object.errors.full_messages.each do |sentence| %>
            <li class="error-message"><%= sentence %></li>
        <% end %>
    </ul>
</div>

app/views/products/_form.html.erb
<div class="form-input">
    <%= form.label :name, 'Name' %>
    <%= form.text_field :name, placeholder: 'Name'  %>
</div>
<div class="form-input">
    <%= form.label :description, 'Description' %>
    <%= form.text_area :description, cols: 20, rows: 2, placeholder: 'Description'  %>
</div>
<div class="form-input">
    <%= form.label :price, 'Price' %>
    <%= form.number_field :price, min: 0.00, step: 0.01, placeholder: 'Price' %>
</div>
<div class="form-input">
    <%= form.label :availability %>
    <%= form.select :availability, options_for_select([true, false]), include_blank: "Select an availability" %>
</div>
<div class="form-input">
    <%= form.label :category_id %>
    <%= form.select :category_id, options_from_collection_for_select(Category.all, :id, :name, selected = product.category), prompt: "Select category" %>
</div>

app/views/products/_nested_category.html.erb
<hr>
<h4>Or create a new category:</h4>
<%= f.fields_for :category do |category_fields| %>
    <%= render partial: "categories/form", locals: {f: category_fields} %>
<% end %>

app/views/products/edit.html.erb
<%= conditional_errors(@product) %>

<div class="new-form">
    <header>
        <h2>Edit product</h2>
    </header>
    <%= form_with(model: @product) do |f| %>
        <%= render partial: 'form', locals: {form: f, product: @product} %>
        <%=  render partial: "nested_category", locals: {f: f, product: @product} %>
        <div class="form-button"><%= f.submit %></div>
    <% end %>
    <div class="form-button"><%= button_to "Delete", product_path(@product), method: :delete, data: {confirm: "Are you sure?"} %> <br>
    <%= link_to "New product", new_product_path %>
</div>

app/views/products/index.html.erb
<%= display_h1_conditionally(@category) %>

    <%= form_with(url: products_path, method: :get) do |f| %>
        <%= f.label :search, "Search products by name" %>
        <%= f.text_field :search %>
        <%= f.submit "Search" %>
    <% end %>

<div class="new-form">
    <% @products.each do |product| %>
        <p>Name: <%= link_to product.name, product %> </p>
        <p> Price: US<%= number_to_currency product.price %></p>
        <% if product.availability %>
            <p><%= button_to "Add to cart", order_items_path(:product_id => product.id) %></p> 
        <% else %>
            <p> "Out of stock"</p>
        <% end %>
        <hr>
    <% end %>
</div>

app/views/products/new.html.erb
<%= conditional_errors(@product) %>

<div class="new-form">
    <h1>Create a New Product</h1>

    <%= form_with model: @product do |f|%>
        
        <%= render partial: 'form', locals: {form: f, product: @product} %>
        <%= nested_product_form_conditional(@product, @category, f) %> 
        <hr>
        
        <div class="form-button"><%= f.submit 'Create product' %></div>
    <% end %>
</div>

app/views/products/show.html.erb
  <fieldset>
  <h2><%= @product.name %></h2> 
  
  <p>
    <strong>Description:</strong>
    <%= @product.description %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= link_to @product.category.name, @product.category %>
  </p>
  
  <p>
    <strong>Availability:</strong>
    <%= @product.in_stock? %>
  </p>
  
  <p>
    <strong>Price:</strong>
    <%= number_to_currency @product.price %>
  </p>
  
  <% if @product.availability %>
      <p><%= button_to "Add to cart", order_items_path(:product_id => @product.id) %></p> 
  <% end %>
  </fieldset>

<% if user_admin %>
<%= link_to 'New Product', new_product_path(@product) %> |
  <%= link_to 'Edit Product', edit_product_path(@product) %> |
<% end %>
<%= link_to 'Back', products_path %>