config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

    #signing up
    get '/signup', to: 'users#new'
    post '/signup', to: 'users#create'
  
    #logging in
    get 'auth/:provider/callback', to: 'sessions#omniauth'
    get '/login', to: "sessions#new"
    post '/login', to: "sessions#create"
    delete '/logout', to: "sessions#destroy"

  #get 'popular_category' => "popular_category"  
  resources :categories do
    resources :products, only: %i[index new create]
  end

  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"

  post 'order_items/:id/add' => "order_items#add_quantity", as: "order_item_add"
  post 'order_items/:id/reduce' => "order_items#reduce_quantity", as: "order_item_reduce"
  post 'order_items' => "order_items#create"
  get 'order_items/:id' => "order_items#show", as: "order_item"
  delete 'order_items/:id' => "order_items#destroy"

  resources :users, except: :new
  resources :products
  resources :admins
  resources :orders
 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  # get '/users/reset_password', to: 'users#reset_form'
  # post '/users/reset_password', to: 'users#password_reset'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MumshieOnlineStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav>
    <div class="navbar-list">
        <a class="navbar-link <%= active_css(root_path)%>" href="/">Home</a>
        <a class="navbar-link <%= active_css(categories_path)%>" href="/categories">Categories</a>
        <a class="navbar-link <%= active_css(products_path)%>" href="/products">Products</a>

        <% if logged_in? %> 
          <% if user_admin %>
            <a class="navbar-link <%= active_css(new_category_path)%>" href="/categories/new">New Category</a>
            <a class="navbar-link <%= active_css(new_product_path)%>" href="/products/new">New Product</a>
          <% end%>
          <a class="navbar-link <%= %>" href="/carts/show">View Cart</a>
          <%= button_to "Logout", logout_path, method: :delete, class: "navbar-link active_css(root_path)" %>
        <% else %>
          <a class="navbar-link <%= %>" href="/carts/show">View Cart</a>
          <%= button_to "Log In", login_path, method: :get, class: "navbar-link active_css(root_path)" %>
          <%= button_to "Sign Up", signup_path, method: :get, class: "navbar-link active_css(root_path)" %>
        <% end %>
        
      
      </div>
    
  </nav>
  <div class="content">

      <% if flash[:success] %>
        <p class="success"><%= flash[:success] %></p>
        <% else flash[:error]%>
        <p class="error"><%= flash[:error] %></p>
      <% end %>
  
      <%= yield %>

  </div>
</body>
<footer class="site-footer">

  <div class="container">
    <div class="row">
      <p class="copyright-text">Copyright &copy; 2021 All Rights Reserved by Mumshie.</p>
    </div>
  </div>
</footer>
</html>